apiVersion: v1
kind: Pod
metadata:
  name: kube-slither
  #namespace: default
spec:
  restartPolicy: OnFailure
  nodeSelector:
    nvidia.com/gpu.workload.config: container

  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"

  containers:
    - name: gpu-container
      image: ghcr.io/gregor-waelchli/kube-slither:v0.1.4
      resources:
        limits:
          cpu: 4
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: 2
          memory: 4Gi
